package com.tinymooc.common.domain;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FriendliLink generated by hbm2java
 */
@Entity
@Table(name = "friendli_link", catalog = "tinymooc")
public class FriendliLink implements java.io.Serializable {

	private String friendlyLinkId;
	private String linkName;
	private String url;

	public FriendliLink() {
	}

	public FriendliLink(String friendlyLinkId) {
		this.friendlyLinkId = friendlyLinkId;
	}

	public FriendliLink(String friendlyLinkId, String linkName, String url) {
		this.friendlyLinkId = friendlyLinkId;
		this.linkName = linkName;
		this.url = url;
	}

	@Id
	@Column(name = "FRIENDLY_LINK_ID", unique = true, nullable = false, length = 32)
	public String getFriendlyLinkId() {
		return this.friendlyLinkId;
	}

	public void setFriendlyLinkId(String friendlyLinkId) {
		this.friendlyLinkId = friendlyLinkId;
	}

	@Column(name = "LINK_NAME", length = 50)
	public String getLinkName() {
		return this.linkName;
	}

	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}

	@Column(name = "URL", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
