package com.tinymooc.common.domain;

/**
 * Created by 哓哓 on 2015/11/30 0030.
 */

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "tinymooc")
public class Grade implements java.io.Serializable {
    private String gradeId;
    private User user;
    private String gradeObject;
    private Double mark;

    public Grade() {
    }

    public Grade(String gradeId) {
        this.gradeId = gradeId;
    }

    public Grade(String gradeId, User user, String gradeObject, Double mark) {
        this.gradeId = gradeId;
        this.user = user;
        this.gradeObject = gradeObject;
        this.mark = mark;
    }

    @Id
    @Column(name = "GRADE_ID", unique = true, nullable = false, length = 32)
    public String getGradeId() {
        return this.gradeId;
    }

    public void setGradeId(String gradeId) {
        this.gradeId = gradeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "GRADE_OBJECT", length = 32)
    public String getGradeObject() {
        return this.gradeObject;
    }

    public void setGradeObject(String gradeObject) {
        this.gradeObject = gradeObject;
    }

    @Column(name = "MARK", columnDefinition="double(3,2) default '0.00'")
    public Double getMark() {
        return this.mark;
    }

    public void setMark(Double mark) {
        this.mark = mark;
    }

}

