package com.tinymooc.common.domain;

/**
 * Created by 哓哓 on 2015/11/26 0026.
 */

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * HeadImage generated by hbm2java
 */
@Entity
@Table(name = "head_image", catalog = "tinymooc")
public class HeadImage implements java.io.Serializable {

    private String imageId;
    private String imageLarge;
    private String imageMid;
    private String imageSmall;
    private Date createDate;
    private Set<Team> teams = new HashSet<Team>(0);
    private Set<User> users = new HashSet<User>(0);

    public HeadImage() {
    }

    public HeadImage(String imageId) {
        this.imageId = imageId;
    }

    public HeadImage(String imageId, String imageLarge, String imageMid,
                     String imageSmall, Set<Team> teams, Set<User> users) {
        this.imageId = imageId;
        this.imageLarge = imageLarge;
        this.imageMid = imageMid;
        this.imageSmall = imageSmall;
        this.teams = teams;
        this.users = users;
    }

    @Id
    @Column(name = "IMAGE_ID", unique = true, nullable = false, length = 32)
    public String getImageId() {
        return this.imageId;
    }

    public void setImageId(String imageId) {
        this.imageId = imageId;
    }

    @Column(name = "IMAGE_LARGE", length = 100)
    public String getImageLarge() {
        return this.imageLarge;
    }

    public void setImageLarge(String imageLarge) {
        this.imageLarge = imageLarge;
    }

    @Column(name = "IMAGE_MID", length = 100)
    public String getImageMid() {
        return this.imageMid;
    }

    public void setImageMid(String imageMid) {
        this.imageMid = imageMid;
    }

    @Column(name = "IMAGE_SMALL", length = 100)
    public String getImageSmall() {
        return this.imageSmall;
    }

    public void setImageSmall(String imageSmall) {
        this.imageSmall = imageSmall;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "headImage")
    public Set<Team> getTeams() {
        return this.teams;
    }

    public void setTeams(Set<Team> teams) {
        this.teams = teams;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "headImage")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DATE", length = 19)
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}

