package com.tinymooc.common.domain;

/**
 * Created by 哓哓 on 2015/12/6 0006.
 */


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "tinymooc")
public class Resource implements java.io.Serializable {

    private String resourceId;
    private String resourceObject;
    private String type;
    private Video video;
    private Link link;
    private ImageText imageText;

    public Resource() {
    }

    public Resource(String resourceId) {
        this.resourceId = resourceId;
    }

    public Resource(String resourceId, String resourceObject, String type,
                    Video video, Link link, ImageText imageText) {
        this.resourceId = resourceId;
        this.resourceObject = resourceObject;
        this.type = type;
        this.video = video;
        this.link = link;
        this.imageText = imageText;
    }

    @Id
    @Column(name = "RESOURCE_ID", unique = true, nullable = false, length = 32)
    public String getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    @Column(name = "RESOURCE_OBJECT", length = 32)
    public String getResourceObject() {
        return this.resourceObject;
    }

    public void setResourceObject(String resourceObject) {
        this.resourceObject = resourceObject;
    }

    @Column(name = "type", length = 50)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "resource")
    public Video getVideo() {
        return this.video;
    }

    public void setVideo(Video video) {
        this.video = video;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "resource")
    public Link getLink() {
        return this.link;
    }

    public void setLink(Link link) {
        this.link = link;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "resource")
    public ImageText getImageText() {
        return this.imageText;
    }

    public void setImageText(ImageText imageText) {
        this.imageText = imageText;
    }

}

